- npm-shrinkwrap.json
- package.json
> chore(Unit Tests): Fix webpack error in unit tests

- app/styles/_quickview.scss
Added change of cursor to pointer for screenshots to show that they can be clicked
> fix(styling): #251 Added pointer cursor

- app/js/components/createEdit/index.jsx
- app/styles/_sweetalert.scss
- app/styles/main.scss
Added overrides for SweetAlert styling
> fix(style): Updating SweetAlert styling

- app/js/components/NavBar/helpmodal.jsx
- package.json
@wski , @hoganmaps  When you get a chance, please have a look.
> Add Docs and Videos to help modal #278

- app/js/components/quickview/Header.jsx
> fix(Quickview): Previewing listing from create/edit displays error in console. #422

- app/js/components/createEdit/index.jsx
> fix(CreateEdit): Populate ContactType dropdown correctly

- app/js/main.js
Related ozp-react-commons PR needs to be checked out for this to work
> feat(lt IE 10): Redirect users below IE10 away

- app/js/components/discovery/index.jsx
> fix(SearchBar): Clicking 'x' on the searchbar now only clears searchbar

- app/js/webapi/Listing.js
> fix(URL redirect):  Avoids browser redirects by adding trailing slash

- app/js/components/createEdit/index.jsx
> fix(Create Edit): Missing labels for owners and contacts

- app/styles/_carousel.scss
> fix(QuickView):  Screenshot carousel bar misaligned 

- app/js/components/discovery/index.jsx
> feat(Infinite Scroll): loading more is now more obvious #534

- app/js/components/management/mall/Categories.jsx
- app/js/components/management/mall/ContactTypes.jsx
- app/js/components/management/mall/Intents.jsx
- app/js/components/management/mall/Organizations.jsx
- app/js/components/management/mall/Stewards.jsx
- app/js/webapi/Notification.js
We should still discuss #539.
But for now we need to be consistent because the redirects are causing issues in our staging environment.
> chore(redirects): Conform to django standard of mandatory trailing slash

- app/js/components/management/AllListings/index.jsx
> fix(All Listings): Fix APPS_MALL_STEWARD view of all listings.

- app/js/actions/ProfileSearchActions.js
- app/js/components/discovery/index.jsx
- app/js/components/quickview/index.jsx
- app/js/tour/centerTour.js
> fix(Tour): Close tour at end of tour

- app/js/components/quickview/reviews/index.jsx
Please review #491 
@clarkjefcoat 
@wski
> 491: fixed IconRating issue

- app/js/components/shared/ChangeLog.jsx
Please review:
@clarkjefcoat 
@wski
> 567 - fixed by adding agency for

- package.json
> chore(version):  Force the use of node-sass@3.4.2

- app/js/webapi/Listing.js
> Record searches in metrics

- app/js/components/createEdit/index.jsx
Fixed. Please use the use-case in the above thread to test.
@wski 
@akonsowski 
@clarkjefcoat
> Create/Edit page - Unnecessary "Could not save!" message

- app/js/components/createEdit/form/MarkingInput.jsx
@clarkjefcoat 
@wski
Please review and test.
> Create/Edit Page - Invalid portion markings are allowed #588

- app/js/components/management/user/RecentActivity.jsx
@clarkjefcoat 
@mannyrivera2010
> Listing Management - Recent Activity should show icons #587

- app/styles/main.scss
@clarkjefcoat 
@wski 
@SOAP1914
> FIREFOX and CHrome ONLY- Thin black box displays around screenshots #572

- package.json
> chore(versioning): Use the latest version of babel

- npm-shrinkwrap.json
> chore(shrinkwrap): Explicit commits of internal projects removed

- app/js/components/management/AllListings/index.jsx
- app/js/components/management/shared/ApprovalStatusFilter.jsx
- app/js/components/management/user/RecentActivitySidebar.jsx
…issue where reacent activity was not linking to all listings this pull request will fix #578  and #619 but @mannyrivera2010 deleted counts will need a backend change to count deleted apps
@rkenyon1969 @wski @SOAP1914 @clarkjefcoat
> 578 management

- app/js/components/NavBar/notificationsmodal.jsx
> chore(cleanup): Unnecessary parens

- app/js/components/management/mall/notifications/CreateNotification.jsx
@clarkjefcoat @mannyrivera2010 @akonsowski
> feat(Notifications): increase notification length to 600 characters

- app/js/components/createEdit/form/ImageInput.jsx
- app/js/components/createEdit/form/__tests__/ImageInput-test.js
- app/js/webapi/Image.js
fixed create edit forms to include am image verification. also added tests to the input
@wski 
@clarkjefcoat 
@rkenyon1969 
@SOAP1914
> 188 create edit

- app/js/components/management/mall/Categories.jsx
#641 
@mannyrivera2010 @rkenyon1969 @wski @SOAP1914
> fix(categories):extra slash is causing errors on backend

- app/js/components/createEdit/form/ImageInput.jsx
made UI changes according to beth [#188](https://github.com/ozone-development/ozp-center/issues/188) @rkenyon1969 @wski @SOAP1914
> fix(createedit): made changes to message according to beth #188

- app/js/components/discovery/index.jsx
@wski @akonsowski @rkenyon1969
> fix(Search)Made search result tab to main content

- app/js/main.js
@clarkjefcoat 
@wski 
@akonsowski 
Please review
> Fix(Bookmark): #649: Added jS code to polyfill str.includes

- app/js/components/createEdit/form/ListInput.jsx
#194 
@wski @rkenyon1969 @clarkjefcoat
> fix(listinginput):listings have been limited to 10 inputs

- app/js/utils/timeAgo.js
> feat(TimeDate): If timestamp is more than 24 hours old show date

- app/js/components/BookmarkButton.jsx
mvd and modified componenetWillUpdate() to componentDidUpdate() and modified toggleInLibrary()
@clarkjefcoat 
@akonsowski 
@wski
> Fix(Bookmark): #656: issue with get.Library()

- app/js/components/NavBar/notificationsmodal.jsx
> fix(Notifications Modal): Show listing name, don't show authors.

- .eslintignore
- app/js/components/discovery/index.jsx
- app/js/utils/typeahead.js
> feat(TypeAhead): Added typeahead to center

- .eslintignore
- app/js/components/NavBar/notificationsmodal.jsx
@rkenyon1969 @clarkjefcoat @arw180
> feat(Shared Folders): Shared folders additions

- app/js/components/NavBar/index.jsx
- app/js/stores/CurrentListingStore.js
#687  added in checks to make sure user has access to features
@skhtet @rkenyon1969 @wski
> 687 security

- package.json
having the fs package install was breaking travis build
[source](https://github.com/npm/npm/issues/13743)
> fix(package):fs package is now part of the npm core

- package.json
Reverts aml-development/ozp-center#696
> Revert "fix(package):fs package is now part of the npm core"

- app/js/components/NavBar/index.jsx
changes reflect newest change to backend
@wski @rkenyon1969 @skhtet
> feat(index):changed logic that checks for 2nd party users

- app/js/tour/centerTour.js
- app/js/tour/tour.js
#705 
aml-development/ozp-hud#180
@wski 
@akonsowski 
@blynch11p
> Fix(Tour): Modified Search Step and added code to support Tour in Hud

- app/js/main.js
Fix for issue #709  @skhtet @blynch11p @rkenyon1969
> Fix(SecurityBanner): display different banner for second party users

- app/styles/management/_notifications.scss
Added word wrap. @blynch11p @skhtet @rkenyon1969
> fix(notificationSettings) Fix notification overflow #691

- app/js/components/discovery/index.jsx
- app/js/components/management/AllListings/index.jsx
- app/js/components/management/user/MyListings.jsx
- app/js/components/shared/DeleteConfirmation.jsx
- app/js/stores/DiscoveryPageStore.js
- app/js/stores/GlobalListingStore.js
@akonsowski @blynch11p  #631 fix and #730
> 631 deleted aps return in featured

- app/js/components/createEdit/index.jsx
#722 @blynch11p @lsemesky @rkenyon1969 @mannyrivera2010
> fix(index):changed verbage to say agency

- app/js/components/createEdit/index.jsx
#722 
@mannyrivera2010 @lsemesky @blynch11p
> fix(index):changed verbage from orginization to agencies

- app/js/components/createEdit/index.jsx
- app/js/webapi/Listing.js
added logic to check for validity of certificates
@skhtet @lsemesky @rkenyon1969 @blynch11p
> Konsoa fix3

- app/js/components/quickview/DetailsTab.jsx
@lsemesky @blynch11p @rkenyon1969 @mannyrivera2010 
the routes were not working because navigation was on home page when viewing the model
> fix(details):tags have been updates to work on all browser versions

- app/js/components/quickview/DetailsTab.jsx
clicking the link will open the listing in a new tab
@blynch11p @lsemesky @rkenyon1969
> feat(details): when clicking url to listing it will open in a new tab

- app/js/components/quickview/DetailsTab.jsx
- app/js/components/quickview/ResourcesTab.jsx
@lsemesky @akonsowski @rkenyon1969
> Changed margin-top to marginTop

- app/js/components/quickview/DetailsTab.jsx
@lsemesky @akonsowski @rkenyon1969
> Fixed JS warning about unique keys on DetailsTab

- app/js/actions/ListingActions.js
- app/js/components/app.jsx
- app/js/components/createEdit/index.jsx
- app/js/components/listing/ListingTile.jsx
- app/js/components/management/shared/ApprovalStatusFilter.jsx
- app/js/components/management/shared/TableView.jsx
- app/js/components/management/user/MyListings.jsx
- app/js/components/management/user/RecentActivity.jsx
- app/js/components/management/user/RecentActivitySidebar.jsx
- app/js/components/quickview/AdministrationTab.jsx
- app/js/components/shared/ChangeLog.jsx
- app/js/components/shared/PendingDeleteConfirmation.jsx
- app/js/services/ListingService.js
- app/styles/_quickview.scss
- app/styles/listing/_admin-owner-listing-tile.scss
- app/styles/main.scss
> Pending delete

- app/js/components/quickview/notifications/CreateNotification.jsx
@akonsowski @tdressel @lsemesky
> Added indication of zulu time per AMLNG-314

- app/js/components/createEdit/Sidebar.jsx
> (fix):grammer error in create edit page

- app/js/actions/ListingActions.js
- app/js/components/Routes.jsx
- app/js/components/discovery/DetailedQuery.jsx
- app/js/components/discovery/Sidebar.jsx
- app/js/components/discovery/index.jsx
- app/js/components/header/Logo.jsx
- app/js/components/quickview/DetailsTab.jsx
- app/js/services/ListingService.js
- app/js/stores/DiscoveryPageStore.js
- app/js/webapi/Listing.js
> Taglink fix

- app/styles/_header.scss
Bug fix for JIRA-337. Drop down letters were being cut off
> JIRA-337: Bug fix for drop down letters being cut off

- app/js/components/discovery/RecommendedListingTile.jsx
- app/js/components/discovery/index.jsx
- app/js/components/quickview/Recommendations.jsx
- app/js/components/quickview/index.jsx
- app/js/stores/CurrentListingStore.js
- app/js/stores/DiscoveryPageStore.js
- app/js/stores/GlobalListingStore.js
- app/js/webapi/Listing.js
- app/styles/_discovery.scss
- app/styles/_featured-listings.scss
- app/styles/_quickview.scss
adding recommendation modal on front page. Has commented out code for similar applications in quickview
@mleeBoeing @blynch11p
> Recommendations

- .eslintrc.js
- app/js/components/discovery/DetailedQuery.jsx
Display error message when Back-end fails to perform tasks.
> JIRA-247: Display errors on front-end for ElasticSearch

- app/js/components/NavBar/notificationsmodal.jsx
Please Review:
@mleeBoeing 
@lsemesky 
@blynch11p
> feat(notification): Fixed Link in drop down

- app/js/components/discovery/Sidebar.jsx
Made 'Categories Section' to be more descriptive for 508 users
> Made 'Categories Section' to be more descriptive for 508 users

- app/js/components/discovery/index.jsx
@mannyrivera2010 @blynch11p @mleeBoeing
> JIRA-411 changed recommendation text to "Recommended for You"

- app/js/stores/CurrentListingStore.js
Separating this from mlee's pull request so this can be corrected before his pr is merged
@mleeBoeing @blynch11p
> fixed typo that mlee identified

- app/styles/_quickview.scss
> updated style to fix issue with carousel expanding beyond modal

- app/js/components/shared/ChangeLog.jsx
> Fixing text capitalization consistency

- app/js/components/createEdit/form/InputMixin.jsx
- app/js/components/createEdit/index.jsx
> Add FOUO warning to tags form

- app/js/actions/ListingActions.js
- app/js/components/quickview/AdministrationTab.jsx
- app/js/services/ListingService.js
- app/js/stores/PaginatedChangeLogByIDStore.js
- app/js/webapi/Listing.js
@mleeBoeing @J-Fid @lsemesky 
Removed the unused code in Listing.js.  
Prior PR wasn't updating the Listing Changes when moving between different Application quickview displays.  This should fix that.
>  Changelogs limit

- app/js/components/management/user/index.jsx
- app/js/mixins/TabMixin.js
- app/styles/management/user/_listing-management.scss
Pull the too_many_tabs_data branch from ozp-backend, make dev, and use wsmith to see what the changes do for Listing Management.  A left & right arrow will appear to allow the user to page through the tabs.
@lsemesky @mleeBoeing
> Too many tabs

- app/js/components/discovery/DetailedQuery.jsx
Hard code error message for ES search
> Temp hardcode error message for ES

- app/js/stores/CurrentListingStore.js
Fix for when you try to submit listing and it hangs on the saving listing popup. 
@lsemesky - I have done some tests to make sure this push won't break similar listings. However, please confirm.
> Fix hanging issue when submitting new listing

- app/js/actions/SubscriptionActions.js
- app/js/components/discovery/Sidebar.jsx
- app/js/components/management/user/index.jsx
- app/js/mixins/TabMixin.js
- app/js/stores/SubscriptionStore.js
- app/js/webapi/Subscription.js
- app/styles/_discovery.scss
- app/styles/management/user/_listing-management.scss
Allows subscribe/unsubscribe link to show next to each category
@blynch11p @lsemesky - Please review
> Categories subscribe reflux

- app/js/components/NavBar/index.jsx
Please Review:
@lsemesky 
@mleeBoeing 
@mannyrivera2010 
@blynch11p 
To test, enter something in the search box.  Afterwards, select the center icon to return to the center homepage.
> fix: Selecting the center icon now takes the user to the Center Homepage.

- app/js/components/management/mall/notifications/ActiveNotification.jsx
- app/js/components/management/mall/notifications/PastNotification.jsx
The Center Settings->Notifications->Active/Past Notifications code also needed the update to display the HTML formatted notifications
@J-Fid @lsemesky @mannyrivera2010 @rkenyon1969 @mleeBoeing
> Another location that needed updating for new notification styling.

- app/js/components/discovery/Sidebar.jsx
Subscription links currently break when a new category gets added. This is a fix for that.
> Fix bug where adding new category messes up with subscription links

- app/js/actions/SubscriptionActions.js
- app/js/components/Routes.jsx
- app/js/components/discovery/DetailedQuery.jsx
- app/js/components/discovery/Sidebar.jsx
- app/js/components/discovery/index.jsx
- app/js/components/quickview/DetailsTab.jsx
- app/js/stores/SubscriptionStore.js
- app/js/webapi/Listing.js
- app/js/webapi/Subscription.js
- app/styles/_discovery.scss
Need to pull backend branch as well: https://github.com/aml-development/ozp-backend/pull/309
> Initial commit for tag subscription

- app/js/components/discovery/DetailedQuery.jsx
> Fix symbol iterator bug

- app/js/components/management/mall/notifications/ActiveNotification.jsx
- app/js/components/management/mall/notifications/PastNotification.jsx
- app/js/components/quickview/notifications/ActiveNotification.jsx
- app/js/components/quickview/notifications/PastNotification.jsx
Show the creation date when displaying notifications. 
Edit: You need to pull backend branch https://github.com/aml-development/ozp-backend/pull/316
> Show the creation date when displaying notifications

- app/js/components/createEdit/OrgStewardModal.jsx
- app/js/components/management/mall/Stewards.jsx
- app/js/components/shared/Crud.jsx
Please Review:
@mannyrivera2010 
@blynch11p 
@skhtet 
@mleeBoeing 
To test saving info in Center Settings:
* Go to Center Settings
* Edit content in any of the tabs
* Select save
* Observe that changes were saved
To test demotion of an Org Steward:
* Navigate to Center Settigns -> Stewards
* Select a steward
* Select the Demote button and attempt to remove the steward
* Observe successful removal of steward
* Observe the grid refreshes with removed steward no longer appearing
Error handling:
* Attempt to select the Demote button without selecting a steward
* Observe error message appears
* Attempt to demote the last steward in the list
* Observe error message appears
> fix/feature: Selecting the save button in Center Settings now properly saves information.  Added demote button to Stewards tab to demote stewards.

- app/js/components/discovery/ListingTile.jsx
- app/js/components/discovery/RecommendedListingTile.jsx
- app/js/components/quickview/Header.jsx
- app/js/components/shared/IconRating.jsx
- app/styles/_quickview.scss
- app/styles/main.scss
Show total rating count for each listing
> Initial commit to show total rating count

- app/js/stores/CurrentListingStore.js
A fix for the fix of the fix of viewing/editing listings.
Things to check:
Load a listing from Center
Refresh page and make sure the listing loads
Create/Edit/Submit a listing
Choose 'Edit' on a Listing from the Listing Management->My Listings page
Refresh Edit Listing page
@mleeBoeing @lsemesky @J-Fid
> Another listing store fix

- app/js/components/discovery/DetailedQuery.jsx
- app/styles/_discovery.scss
Enhance design of tag field to include subscribe link within tag box
1. Login to center
2. Search via by tag, should see Subscribe link implemented within the box
https://jira.di2e.net/browse/AMLNG-569
> Initial commit to add subscription link within tag box

- app/js/webapi/Subscription.js
1. Login to center with aaronson
2. Subscribe to a category
3. Unsubscribe to a category
4. Subscribe link should be saying "Subscribe" next to the category
> Fix bug where regular users cannot unsubscribe

- app/js/components/createEdit/form/Toggle.jsx
- app/js/components/createEdit/index.jsx
- app/js/components/quickview/AdministrationTab.jsx
- app/styles/_create-edit.scss
- app/styles/_quickview.scss
The toggles for Preferences now display ON/OFF.  The toggles in the Administration tab for an App should follow the same design.
> Update toggles in Quickview->Administration visually

- app/js/components/management/mall/notifications/CreateNotification.jsx
- app/js/components/management/mall/notifications/PastNotification.jsx
- app/js/components/management/mall/notifications/__tests__/CreateNotification-test.js
- app/js/components/management/mall/notifications/index.jsx
- app/styles/management/_notifications.scss
…st notification.
To test:
- Go to Center Settings -> Notifications
- In the Past Notifications column, there will be a Message icon next to the Create/Expired dates.
Click the message icon.
- The message will populate the Notification Text textearea in the Send a Notification column.
- Complete the notification form (select a date) and click Send.
Verify the Notification is sent with the correct text.
Other tests:
Make sure a pre-populated notification can be edited and sent correctly.
Verify the Reset button functions correctly.
Verify form resets after sending a notification (both created from pre-populate and from manually typing)
@mleeBoeing @lsemesky @rkenyon1969
> Notification resend

- app/js/stores/GlobalListingStore.js
- app/js/webapi/Listing.js
To test, checkout backend branch simplify_storefront_1
Make sure that no information is missing from the listing icons in storefront (check bookmarks, launch shortcut, edit, stars, title etc)
make sure info still loads into app detail modal
make sure editing still works from listing icon and detail modal
> updated stores to fetchById on every app open

- app/js/components/createEdit/form/InputMixin.jsx
- app/styles/_create-edit.scss
Change styling of FOUO bar in Tags in Create Listing
> Change styling of FOUO bar in Tags

- app/js/components/quickview/DetailsTab.jsx
- app/styles/_quickview.scss
- consistent layout for Header/sub-header/item
- consistency with line height in layout
- proper wrapping of long strings
View AMLNG-390 for screenshots
> Fix spacing issues in Modal->Details

- app/js/components/management/mall/Stewards.jsx
- app/js/components/shared/Crud.jsx
Takes care of the modal style consistency issue for removing an org steward. Handles the removal differently than previously completed.
@mleeBoeing @lsemesky
> A slightly different way to handle removing org stewards.

- app/js/components/management/mall/Stewards.jsx
- app/js/components/shared/Crud.jsx
Changed demote keyword to removeUser to improve readability. Corresponding issue #848
> refactored code to improve readability

- app/js/components/discovery/index.jsx
- app/js/services/ListingService.js
- app/styles/_discovery.scss
Create a loading indicator when items are loading on storefront. The indicator will be a circle spinning infinitely.
> Have loading indicator for storefront

- app/js/components/createEdit/OrgStewardModal.jsx
To test:
Go to Submit Listing page
Click the 'View list of organization stewards' link.
Verify the modal has the title bar with the X.
@mleeBoeing, @flesher1, @rkenyon1969, @lsemesky
> Adding back the Org Steward modal title

- app/js/components/NavBar/index.jsx
- app/js/utils/typeahead.js
- app/styles/_quickview.scss
related tickets:
https://github.com/aml-development/ozp-center/issues/863
https://github.com/aml-development/ozp-center/issues/861
https://github.com/aml-development/ozp-center/issues/860
> Center style fixes

- app/js/components/discovery/ListingTile.jsx
- app/js/webapi/Listing.js
To test:
Prior to pulling, notice that the count, next to the stars, is missing in center listing tiles
eg: * * * * * 
After pulling, the count will return
eg: * * * * * (5)
@rkenyon1969 @flesher1 @mleeBoeing
> Fixing displaying the listing review total count in tiles

- app/js/components/quickview/index.jsx
@flesher1 @tdressel @rkenyon1969 @skhtet
> Correcting the spelling in the disabled/deleted listing popup

- app/js/components/discovery/RecommendedListingTile.jsx
- app/js/components/discovery/RecommendedListingTileStorefront.jsx
Look at the Recommender listings in Center and verify Listing with ratings have the count visible
*****(4)
> Fixing the missing rating count in the recommender tiles

- app/js/tour/centerTour.js
Fixing the spelling of 'separate'. (JIRA-799)
> Spelling fix in Tour

- app/js/components/management/__tests__/AllListings-test.js
- app/js/components/management/__tests__/OrgListings-test.js
- app/js/components/quickview/__tests__/AdministrationTab-test.js
- app/js/components/shared/__tests__/IconRating-test.js
- app/js/mixins/AjaxMixin.js
- app/js/mixins/TabMixin.js
- app/js/services/ListingService.js
- app/js/stores/CurrentListingStore.js
- app/js/stores/DiscoveryPageStore.js
- app/js/stores/UnpaginatedListingsStore.js
- app/js/stores/__tests__/PastNotificationStore-test.js
- app/js/tour/centerTour.js
Fix eslint errors in our js folder
> style(ozp): address all eslint errors

- package.json
Note from github - https://github.com/aml-development/ozp-center/blob/master/package.json
We found a potential security vulnerability in one of your dependencies.
The moment dependency defined in package.json has a known high severity security vulnerability in version range < 2.11.2 and should be updated.
Need to update our dependency and test that nothing is affected. (And/or remove the package if it's not being used.
This will fix the vulnerability.
> chore(packages): update moment.js to patch vulnerability

- app/js/components/management/mall/notifications/ActiveNotification.jsx
- app/js/components/management/mall/notifications/PastNotification.jsx
AMLNG-700: Bookmark Folder / un-delete button
- ability to restore deleted folder
- undelete button with instructions
- un-delete warning/popup
- notification with link to restore folder
To test:
The `undo_delete_folder` branches are needed from ozp-hud/ozp-center/ozp-backend/ozp-react-commons.
- Log into HUD with any user.
- If the user does not already have bookmarks & bookmark folders, find listings to bookmark, and create some folders.
- Choose the Delete option from any Folder menu.
Results:
Banner is displayed alerting the user the folder was deleted.
The **undo** link will restore the folder
The banner will go away after 10 seconds if not interacted with
The user can click the X in the banner to close it.
- Refresh the page
Results:
A new notification will be …
> AMLNG-700: Undo Delete Folder

- app/js/tour/centerTour.js
fixes the recommender tour step to display the title "Recommended For
You" to match site wording.
Closes #AMLNG-871
> fix(tour): fix tour wording

- app/styles/_carousel.scss
Add styling to support older browsers
> fix(carousel): Styling fix

- app/styles/_carousel.scss
The ordering was still incorrect in staging.  This appears to be better.
> Reordering the flex styles for carousel

- app/js/components/quickview/index.jsx
Adds beeter checking for user access to listings through all stages of
listing lifcycle.
Corrects issues with listing owner access.
Closes #AMLOS-451
As an owner I cannot access a returned or pending deletion listing without an admin re-enabling the listing for me.
review who should and should not be able to access a listing when it is returned or pending deletion.
Allow an owner and applicable stewards to access listings given any state other than deletion.
**How To Test**
Pull this branch. 
With jones put listings into the states:
Approved, Pending Deletion, Rejected deletion, rejected submission, Pending org, Pending, Approved&disabled, draft, and deleted.
Check access with the following users:
bigbrother (all but deleted), Jones(all but deleted), …
> fix(access): fix listing access issues
