aml-development/ozp-center

app/js/components/NavBar/helpmodal.jsx
This fixes the issue where if you were logged in as an `APPS_MALL_STEWARD` help would be broken in the modal.
@clarkjefcoat @SOAP1914 please review.
=> fix(Help): Fixed invalid role for appsmall stewards #518

app/js/components/createEdit/index.jsx
This PR depends on https://github.com/ozone-development/ozp-react-commons/pull/48
This is a follow up on ticket #533.  The previous fix made the appropriate text display, but broke the saving of changes to the field.
=> fix(Create Edit): Fix display of associated agency

package.json
We are not compatible with the 3.1.x releases of gulp-bless, because that uses bless 4.  See
https://github.com/BlessCSS/gulp-bless/commits/master
https://github.com/BlessCSS/bless/issues/93
=> fix(package.json): Use a version of gulp-bless that uses bless 3.x.x

app/js/components/NavBar/notificationsmodal.jsx
Fix for issue #617 where the see more notifications when clicked on displayed the wrong notification in the right of the pop up window.
=> (fix) 617 display wrong notification

app/js/components/NavBar/notificationsmodal.jsx
Fix for displaying notification's date one month ahead.  date.getMonth() returns 0-11 which matches up with the array indexes thus +1 wasn't necessary
@clarkjefcoat 
@wski 
@akonsowski
=> fix(notification): Display Correct Date #625

app/js/components/quickview/reviews/EditReview.jsx, app/js/components/quickview/reviews/UserReviews.jsx, app/js/components/quickview/reviews/__tests__/EditReview-test.js, app/js/components/quickview/reviews/__tests__/UserReviews-test.js
#693 #692 #679 
only admins/ org stewards should be able to delete reviews from anyone review authors should only be able to delete / edit their own reviews and 2pi users will only be able to submit a review and not be able to edit it.
@wski @skhtet @rkenyon1969
=> fix(reviews):removed edit icon for masked users

app/js/components/quickview/reviews/EditReview.jsx
#679 
when viewing a review that is not the current users the edit box will be deactavited
@wski @skhtet @rkenyon1969
=> fix(editreview):disabled review editing except for own reviews

app/js/components/carousel/index.jsx
Fixed the arrow buttons disappearing by moving them into the parent container so that they did not move when tabbing @akonsowski @blynch11p
=> fix(Carousel): Fixed arrows disappearing when tabbing into carousel #524

app/js/stores/ActiveNotificationStore.js
@lsemesky @akonsowski @rkenyon1969 
The notifications were being built on top of each other over and over causing non-unique keys, this re-inits the notifications after a completed fetch.
=> Re-init-ing Notifications after a new fetch.

app/js/components/management/mall/notifications/CreateNotification.jsx
@lsemesky @akonsowski @tdressel 
Changing the Zulu Time to Z to match the other commit for consistency.  There's no need to spell out Zulu.
=> Updating for site-wide consistency.

app/styles/management/user/_my-listings.scss
@blynch11p @mleeBoeing in order to give a thumbs up for this you need to checkout this branch and make sure it works according to the following details:
Other categories word wrap in line with the first word when browser is resized. May need to add a missing css class somewhere to conform
Then either :+1:  (+1 inside of colons) or leave comments on the code
=> fixed pending deletion alignment

app/js/webapi/__tests__/api-listing-response.js
ozp-center, ozp-backend, and ozp-react-commons all have this typo and a PR to match. (Civilian vs Civillian)
@mannyrivera2010 @lsemesky @mleeBoeing @J-Fid
=> Fixing a typo (-center)

app/js/analytics/ozp-analytics.js, app/js/components/discovery/ListingTile.jsx, app/js/components/discovery/RecommendedListingTile.jsx, app/js/components/discovery/index.jsx, app/js/components/quickview/Recommendations.jsx
Needs the recommender_constants branch from ozp-react-commons.
After adding the code, you can see the tracking being sent through the browser to Piwik when clicking a Recommended or Similar Listing tile.
Piwik UI will show the events.
@lsemesky @mleeBoeing @rkenyon1969
=> Adding tracking to the Recommended and Similar Listing tiles.

app/js/components/shared/ChangeLog.jsx
Correcting a minor bug that was putting a `this.state.changeLog is undefined` message in the browser console if a user continuously clicked the Enabled and Featured toggles in the Adminisrtation tab of an Application.
@lsemesky @mleeBoeing @rkenyon1969 @J-Fid
=> Putting checks in place for changeLog to not be undefined

app/js/components/management/mall/Stewards.jsx
Please review:
@mannyrivera2010 
@mleeBoeing 
@blynch11p 
@seenusuvarna 
In Center Settings -> Stewards, where it once said demote now says remove.
=> fix: Changed caption and hint fields from 'demote' to 'remove.'

app/js/components/discovery/Sidebar.jsx, app/styles/_discovery.scss
… subscribe link
Edit a category name or two to make it much longer (Center Settings -> Categories):
Make sure the category names and (un)subscribe links on Center don't interfere with each other.
Also, resize the browser window (max) and shrink it width wise and verify nothing looks 'off'
@mleeBoeing @J-Fid @lsemesky @rkenyon1969
=> Sub long cat names

app/js/components/discovery/index.jsx
Issue: sort by state does not change or reflect accurately sort order of returned results when clicking on a category from center home:
STR:
On "Center Home" sort "Most Popular" by "Title: Z to A"
Click on "Communication" Category in left navigation
Results: return results are in default state but sort by state is still "Title: Z to A" which does not match order of returned results
Expected Results: sort by state matches order of return results or state defaults to "Sort By"
Same happens with filtering on Listing Type or Organizations. The Search box does reset the state of the Sort By menu.
=> Fix sort by after new category/orginzation/type changes

app/js/components/discovery/RecommendedListingTile.jsx, app/styles/_quickview.scss
There was also a side-effect of the URL not updating that would make a Similar Listing that was loaded be stuck on the tab (Details/etc) the Quick View was on before loading that Similar Listing.
To test:
Use user bettafish
Prior to pulling branch, open a listing from Center, refresh page, click Details tab, after Similar Listings loads, click a listing to load:
Notice the URL does not change
In some cases, when clicking the tabs in quick view after loading the Similar Listing the tabs will not function as expected (the url will update, but not the display)
Pull the branch, following above steps above while making sure the URL updates as expected after choosing a Similar Listing, and the listing goes to the Overview tab.
Also verify that the tabs in the Similar Listing behave as expected. …
=> Update url after clicking a Similar Listing

app/js/components/discovery/index.jsx, app/js/stores/DiscoveryPageStore.js
Fix sort by issue when doing Ratings -> Low to High. If the ratings were equals, the tie breaker would be the total # reviews (most would show up first). Now it should be the opposite (most total # reviews should show last).
=> Fix Lo to Hi issue with total ratings

app/js/actions/ListingActions.js, app/js/components/discovery/index.jsx, app/js/services/ListingService.js, app/js/stores/DiscoveryPageStore.js, app/js/stores/GlobalListingStore.js, app/js/webapi/Listing.js
to run locally:
make sure you checkout the master backend branch
make sure you pull the latest into the master backend branch
make dev on backend if needed
make reindex_es on backend if needed
checkout this frontend branch
to test:
open developer tools, the network tab
Make sure that when storefront loads there are no references to 
http://127.0.0.1:8001/api/storefront/
and instead are references to the following endpoints
http://127.0.0.1:8001/api/storefront/featured
http://127.0.0.1:8001/api/storefront/recent
http://127.0.0.1:8001/api/storefront/most_popular 
http://127.0.0.1:8001/api/storefront/recommended
Ensure that recommended recomendations still only appear for the beta users (eg. bettafish)
Ensure that store front, search, and clicking on apps still function
=> Separating the frontend storefront calls to use the new endpoints

app/js/components/createEdit/index.jsx, app/js/components/createEdit/validation/listing.js
Update disclaimer message on Categories section in Create Listing page. Should show red error when no categories selected and when more than 3 are selected.
Must have the disclaimer branch in ozp-react-commons in your node_modules:
https://github.com/aml-development/ozp-react-commons/pull/88
=> Change disclaimer for Categories in Create Listings Page

app/js/components/discovery/index.jsx, app/js/stores/DiscoveryPageStore.js
Go to Homepage
Go to Most Popular section ( Sorted by default by most popular apps)
Choose Sort by Z-A 
RESULTS - The apps in Most Popular section are sorted now Z-A
Choose a category filter
RESULTS - The results display all apps by category.  Sort By is defaulted.
Go back to Homepage, Go to Most Popular Section.
RESULTS - The Most Popular Section displays default Sort By state but the actual section is sorted by Z-A.
EXPECTED RESULTS - It should have defaulted back to its original most popular sort by state
=> Fix the sorting when returning back to storefront

app/js/actions/NotificationActions.js, app/js/components/management/mall/notifications/ActiveNotification.jsx, app/js/components/management/mall/notifications/PastNotification.jsx, app/js/components/shared/Crud.jsx, app/js/components/shared/DeleteConfirmation.jsx, app/js/stores/ActiveNotificationStore.js, app/js/stores/PastNotificationStore.js, app/js/webapi/Notification.js
As an admin, I want the ability to delete notifications so that I can manage active and past notification lists.
Delete option appears next to notification on Center Settings>Notifications page
When user selects to delete the notification will be permanently deleted
=> Allow ability to delete Notification in Center Settings

app/js/components/quickview/Recommendations.jsx
Similar listings would not show the correct ratings in the quick view modal. The top left would update however the bottom bar wouldn't update. 
Sign in as bettafish
Go to Air Mail
Go to Air Mail 2 and add a review
Go back to Air Mail and you should see the updated review
=> Fix bug where apps not reflecting the correct rating in similar listings

app/js/components/NavBar/index.jsx, app/js/components/app.jsx, app/js/components/notification/NotificationWindow.jsx
Requires using ozp-react-commons#notificationRefactor
See tickets 603, 655, 600, 656
Acceptance criteria 603:
That hud and center have the same user experience (I don't think the font colors for the notification sidebar differing is important)
HUD Before:
Center Before: (The version we want all to use)
Acceptance criteria 655:
STR-
Log on as bigbrother
Share a folder with wsmith
Log on as wsmith
See the notification modal
RESULTS - "bigbrother has shared a the folder with you"
EXPECTED RESULTS - Should say "bigbrother has shared the folder {foldername} with you"
Ticket 600:
As a developer, I would like to access notifications modal from a link so I can embed the link in email notifications.
Hyperlink that will take user to notifications modal: …
=> Notification refactor

app/js/actions/ListingActions.js, app/js/components/quickview/reviews/EditReview.jsx, app/js/components/quickview/reviews/ReviewResponses.jsx, app/js/components/quickview/reviews/SubmitResponse.jsx, app/js/components/quickview/reviews/UserReviews.jsx, app/js/components/quickview/reviews/index.jsx, app/js/services/ListingService.js, app/js/stores/CurrentListingStore.js, app/js/webapi/Listing.js, app/styles/_quickview.scss
Allow the ability to respond to reviews
- Users should be able to respond to reviews by clicking the chat bubble icon next to the edit icon
- Users can only respond to their own original review multiple times.
- Users can only edit reviews if the user is editing their own response. Otherwise, the edit icon will not show in the first place
- Reset button
- If creating a new review response, reset button will clear out the text box.
- If editing an existing response, reset button will revert back the text box to original review response text
- Once you click submit, the text box should automatically remove itself.
- To close the text box, click on the chat bubble icon again.
- Review response text should update automatically if edited.
- Review responses should not reorder upon edit. Should …
=> Allow responding to reviews

app/js/components/discovery/Organizations.jsx, app/js/components/discovery/Types.jsx, app/styles/_discovery.scss
Allow the Type and Organization dropdown menu to have a more descriptive text.
Need to have custom react-select-box to get this to work. Remove existing dependency from node_modules and install the one below
https://github.com/aml-development/react-select-box/pull/3
=> Allow description for listing and organization dropdown in center

app/js/components/quickview/Header.jsx
To test:
Prior to pulling branch, log in to Center using obrien.
Find a Listing under the Minipax org (ex: Wolf Finder)
Open the listing and click the edit button.
Scroll down to the "Private Listing" section and enable the listing as private.
Click Save.
Return to Center, find the Minipax listing that was edited, open the listing, and see that the Lock icon is overlapping the Minipax text.
Pull this branch.
Restart center server
Refresh the browser.
The icon should no longer be overlapping the text.
=> JIRA-750: Fixing the style so the private icon does not overlap

app/js/actions/ListingActions.js, app/js/components/FeedbackButton.jsx, app/js/components/discovery/RecommendedListingTileStorefront.jsx, app/js/services/ListingService.js, app/js/stores/DiscoveryPageStore.js, app/js/webapi/Listing.js
Need backend: https://github.com/aml-development/ozp-backend/pull/372
If user clicks selected thumb, the feedback will be deleted
If user clicks selected thumb, the feedback button will be undone
=> feat(feedback): allow ability to remomve feedback when un-toggled

app/js/components/management/user/RecentActivity.jsx, app/js/components/shared/ChangeLog.jsx
Add log entry to Recent Activity tab in Listing Management.
Add functionality for the 'view' link on review edited and review
created to forward to the reviews tab in a listing modal.
AMLNG-786
As an Admin, I would like to see new listing reviews appear in ListingMngmt>Recent Activity to facilitate Admin notification of posted comments.
• when a user submits review a summary will appear in ListingMngmt>Recent Activity
• the summary will include a link to the review tab of the reviewed listing
• similar to when a review is deleted
~~Test functionality by pulling https://github.com/aml-development/ozp-backend/tree/New_Action_log_addition~~ (Code merged in master.)
After creating a review, there will be an entry in …
=>  feat(activity log): add reviews to activity log

app/js/components/management/mall/notifications/CreateNotification.jsx, app/js/components/shared/Select.jsx, app/styles/management/_notifications.scss
@aml-development/ozp-backend-team 
Requires
ozp-react-commons branch orgstewardNotifications aml-development/ozp-react-commons#105
ozp-backend branch orgstewardNotification (no s at the end) aml-development/ozp-backend#375
Use Case:
An admin has the ability to send out a notification to all Content Stewards, notifying them to review their org's Listings and make any necessary changes.
Content Steward updates Listing as needed via Create New Listing Form (the usual means of updating listings)
Content Steward and listing owner(s) are notified when listing has been updated and approved
Only admins can send notifications to content stewards
All content stewards receive the notification to update their apps
Only content stewards receive the "update app" notification type …
=> Add notification type updated

app/js/components/CenterLaunchLink.jsx, app/js/components/discovery/ListingTile.jsx, app/js/components/discovery/RecommendedListingTileStorefront.jsx, app/styles/_carousel.scss, app/styles/listing/_search-listing-tile.scss
Modify the listing tiles to send the user to listing's reviews by
clicking on the rating in the listing's tile slideup.
Add styling to make new feature more noticable.
Closes AMLNG-580
Add link to the review tab by clicking on the stars in a listing tile.
With center running, go to any of the tiles in center's mall. Hovering over them will bring up the slider. Clicking on the stars or number will send the user to the reviews tab of the listing. Clicking anywhere else in the slider will let the user see the listing.
=> feat(reviews): clicking stars/rating links to reviews

app/styles/_quickview.scss
The Usage and System Requirements sections are broken up using a column-count: 2 style.  But that tries to make the columns even.
I noticed in the Listing 'Tornado', that the Usage Requirements section was broken up and was showing over the System Requirements header. 
This fixes that.
To Test:
Look at Tornado's Launch notice Usage Requirements before pulling code.
Look at Tornado's Launch notice Usage Requirements AFTER pulling code.
=> fix(launch_notice): stop column break in requirements p

app/js/components/CenterLaunchLink.jsx
add system and usage requirements information to launch from thumbnail
view
closes AMLNG-798
Pre-req - Define system and usage requirements in an App Listing. In Profile Settings , Enable the option Show Launch Requirements Notice
Go to Homepage
From Thumbnail view, Launch App from thumbnail view
RESULTS - Sys/Usage requirements pop up displays without the actual system / usage requirements.
EXPECTED RESULTS - Sys/usage requirements from pre-requisites should display on the this pop up.
Open Quick View Modal
Launch App
RESULTS - Sys/usage requirements from the prerequisites display on the pop up as they should.
Pull amlng798 from ozp-backend
Pull amlng798 from ozp-center
=> fix(launch popup): show requirements information

app/js/components/CenterLaunchLink.jsx
add close function on CenterLaunchLink
closes AMLNG-833
Scrollbar disappears once you press the OK button on the launch notice modal. Issue most likely comes from the fact that the OK button is calling a method and forgot to call the closeModal function.
Go to Homepage
From Thumbnail view, Launch App from thumbnail view
Click OK to close modal window
EXPECTED - App returns to normal state with functional scrollbar
RESULTS - Scrollbar no longer allows scroll
Pull amlng833 from ozp-center
=> fix(launch popup): properly close modal when clicking OK

app/js/components/discovery/index.jsx
Add spinner indicator when a back-end call to elasticsearch is performed (category, agency, listing type, text search)
closes AMLNG-810
When filtering Center by category, update page loading process to implement page loading indicator image used when Center page first loads.
Use site data loading indicator image as placeholder until result set is displayed
Same layout as center page
Pull branch amlng810 from ozp-center
=> feat(discovery): show spinner when performing a search

app/js/components/discovery/index.jsx, app/js/components/management/AllListings/index.jsx, app/js/components/management/OrgListings/index.jsx, app/js/components/management/shared/LoadMore.jsx, app/js/components/management/shared/TableView.jsx, app/js/components/management/user/MyListings.jsx, app/js/components/management/user/RecentActivity.jsx, app/js/components/quickview/index.jsx, app/js/components/shared/LoadIndicator.jsx, app/js/components/shared/LoadMore.jsx, app/styles/_discovery.scss
closes AMLNG-805, 806, and 807
Update page loading process for Listing Management>My Listings, All Center Listings, and Recent Activity to use the same loading indicator as when the center page first loads.
Use site data loading indicator image as placeholder until result set is displayed
Same layout as center page
API calls (search, filtering, load more, etc) use load indicator
Both list and table views use load indicator
Pull branch amlng-805-806-807
=> feat(listing management): add load indicators in listing management

app/js/components/management/AllListings/index.jsx
Moves enabled filter to below status in sidebar
Closes #AMLNG-822
**How to test**
Go to listing management, Enabled should be located beneath Status filter in sidebar on left.
=> style(listing managment): move enabled filter

app/js/components/CenterLaunchLink.jsx
When launching a listing from the thumbnail, ensure that the modal popup correctly stacks on top of the UI, meaning the rest of the UI sits under the gray background behind the modal
Go to the center page
Launch a listing from the thumbnail
RESULTS: Main navigation bar, search bar, and carousel arrows are still clickable and sit on top of the modal background
EXPECTED RESULTS: UI components are un-clickable and grayed out under the modal background
Pull modal_stacking_hotfix from ozp-center
=> fix(launch popup): modal correctly stacks on top when launched

app/js/actions/NotificationActions.js, app/js/components/management/mall/notifications/__tests__/CreateNotification-test.js, app/js/components/management/mall/notifications/index.jsx, app/js/stores/ActiveNotificationStore.js, app/js/stores/PastNotificationStore.js, app/js/stores/__tests__/PastNotificationStore-test.js, app/js/webapi/Notification.js
Refactors Notification to fetch the past store and notificaitons in a
method similar to active notifications.
Fixes skipped tests from loader modifications.
Solves store loading issues when making new listing notifications.
Fixes store loading issue when going from listing notification tab to
notification in mall management
AMLNG-857
**How to test**
Pull this branch. Check in listing modal > send notification
and in mall management > notifications
=> refactor(PastNotification): refactor to use store

app/js/components/listing/ListingTile.jsx, app/styles/listing/_admin-owner-listing-tile.scss
Makes disabled listings appear more opaque in this listing management
areas for better visual representation of what is enabled and disabled.
Closes #AMLNG-854
As a user I would like a visual indication in Listing Management that a Listing is enabled or disabled.
Create and icon to display under a Listing in Listing Management if the listing is disabled.
- If a listing is disabled, an icon is visible under the Listing tile in the Listing Management Pages
- The icon does not replace the icon that indicated other status of the Listing, but is displayed near/next to that icon.
**How To Test**
Pull this branch. Go to Listing management. Disable a listing, it should be opaque. create a new listing and take it through the listing creation process. It …
=> feat(listing management): Visual Indicator Disabled

app/js/components/management/AllListings/index.jsx, app/js/components/management/OrgListings/index.jsx, app/js/components/management/shared/LoadMore.jsx, app/js/components/management/user/MyListings.jsx, app/styles/_discovery.scss, app/styles/main.scss, app/styles/management/listings/_listings.scss
AMLNG-858
**Description**     
As a user, I would like all Listing Management tabs to have sort order dropdown option to reorder results and the default sort order to be last modified.
**Acceptance Criteria**   
- when a user clicks on sub tab all results will have the same sort order
- sort order will be last modified
- each tab will have sort order dropdown option to reorder results
For now, the sort options are Last Modified, Newest, Title: A to Z, Title: Z to A, Rating: Low to High, Rating: High to Low, Status.  If no sort option is selected, the backend sort defaults to last modified.
**How to test code**    
Pull `listing_default_sort` from ozp-backend
Pull `listing_mgmt_sortable_grid` from ozp-center
Go to Listing Management
Verify Acceptance Criteria on the list view of both the …
=> feat(listing management): add ability to sort list view

app/js/components/management/mall/notifications/CreateNotification.jsx, app/styles/_discovery.scss
Fix bugs in the profile window on the HUD page.  These bugs are not present when opening the profile on the Center page.
Open the profile window in HUD:
1) Ensure that when loading listings, the spinner icon is centered and animates
2) Ensure that all profile information, including settings and subscriptions, are visible in the window.
Note that you can compare the HUD profile to the correctly working Center profile.  If you spot any differences, then there is a bug/issue.
**How to Test Code**
Pull `fix_profile` from `ozp-center`
Pull `fix_profile` from `ozp-hud`
Pull `fix_profile` from `ozp-react-commons`
Update `package.json` in HUD and Center to point to this branch or your local `ozp-react-commons` repo
=> fix(profile): fix bugs in HUD profile window

app/js/actions/NotificationActions.js, app/js/components/app.jsx, app/js/components/management/mall/notifications/CreateNotification.jsx, app/js/components/shared/MessageQueue.jsx, app/js/components/shared/MessageQueueItem.jsx, app/js/stores/MessageStore.js, app/styles/main.scss
closes AMLNG-863
As a user, I would like to receive feedback when I send a notification, especially long-running system notifications.  When I send a notification, I would like to know that the request is being processed and what the outcome (success / failure) is.
- when the user sends a notification, the UI displays a message indicator informing the user of his/her action
- when the notification is successfully sent to all desired users or fails to be sent, the message indicator updates accordingly
- the user has the ability to hide the indicator in the UI
**How to Test**
Pull `notification_indicator` from `ozp-center`
It may be helpful to update the backend to simulate long notification requests and errors.  To do this, modify the file …
=> feat(loading messages): display loading message for long running back-end tasks

app/js/components/management/OrgListings/index.jsx, app/js/components/management/user/RecentActivitySidebar.jsx, app/js/components/management/user/index.jsx, app/js/mixins/UserRoleMixin.js
AMLNG-801
When I look at an org's listing, the URL contains the organization's title. Instead, it should use the organization's short name to prevent spaces in the URL.
Log in as an Org Steward (ie julia)
Go to Listing Management
Select a tab corresponding to an organization
1) Ensure the URL contains the org's short name instead of the title
2) Ensure the listings are filtered by org appropriately and the counts are correct (both table and grid views). Test sidebar filters too.
3) Ensure that getting to the tab automatically (ie via the Recent Activity Sidebar filters) follows 1-2 as well.
Manually change the URL as follows:
4) Changing the URL from org short name to org title gives an unauthorized alert message and redirects to the Center …
=> fix(listing management): use org short name instead of titles for URLs

app/styles/_carousel.scss
Found out IE needs a different flex/flexbox style for the carousel.  This adds in all of the CSS options to cover various browsers.
Pull code, make sure carousel looks and functions as expected for all available browsers.
=> Fix carousel style again

app/js/components/carousel/index.jsx, app/js/components/management/shared/TableView.jsx, app/js/stores/UnpaginatedListingsStore.js
closes AMLNG-891
In listing management, when a user deletes a listing while in table view, the listing still shows up in the list, even if the status filter is not set to Deleted.  The listing is displayed as deleted, but should not be a part of the list.
Go to Listing Management
Toggle to show the table view
Set the sidebar filter to "Published"
Delete a listing from the table view
RESULTS: Listing displayed as deleted, but shows up in the list
EXPECTED RESULTS: Listing is no longer a part of the "Published" filter and is in the "Deleted" filter
**How to Test Code**
Pull `pending_delete_fix` from `ozp-center`
=> fix(listing management): deleting a listing correctly updates the table view

app/js/components/management/AllListings/index.jsx, app/js/components/management/OrgListings/index.jsx, app/js/components/management/__tests__/AllListings-test.js, app/js/components/management/__tests__/OrgListings-test.js, app/js/components/management/user/MyListings.jsx
closes AMLNG-892
In listing management, when a user toggles between list view and grid view, their state is not always preserved across tabs
Log in as an Org Steward (ie julia) -- you can test with a variety of users, but make sure to test with at least one org steward that has an org listing tab
Go to Listing Management
Toggle between list and table view
RESULTS: Changing tabs does not preserve the list/table view selection
EXPECTED RESULTS: Changing tabs preserves the list/table view selection
**How to Test Code**
Pull `inconsistent_state_fix` from `ozp-center`
=> fix(listing management): make toggling between list and table view consistent through all tabs

app/js/components/management/mall/Intents.jsx, app/js/components/management/mall/__tests__/Intents-test.js, package.json
Upgrade Jquery dependency from 2.1.1 to 3.0.0 and higher.
Updates the tests to work with Jquery3
Closes #AMLNG-919
Breaks intents (Already Broken)
Closes #AMLNG-919
Updates Jquery dependency to remove warning messages in git. 
**How To Test**
pull this branch.
Add react commons https://github.com/aml-development/ozp-react-commons/tree/dependency_update to your package.json file and install it for center and HUD.
Test full site functionality.
The Travis tests will not pass until the above React-commons branch is merged.
=> fix(dependencies): Upgrade Jquery Dependency

app/js/components/quickview/reviews/UserReviews.jsx
Gives admins the ability to delete reviews for listings they do not own.
Closes #AMLOS-540
As a Mall Admin, I cannot delete any reviews that are not created by me.
Users can delete and edit only their reviews
Org stewards can delete reviews for listings they are stewards of. 
Mall admins (site stewards) can delete reviews for any listing.
**How To Test**
Pull this branch
log in as (user below) and check that mallrats review can/cannot be deleted as expected.
Bigbrother: Can Delete
Wsmith: Cannot Delete
Obrien: Can Delete
Johnson: Cannot Delete
Rutherford: Can Delete
=> fix(reviews): admin review deletion fix

app/js/components/quickview/AdministrationTab.jsx
Change text that appears for admins and org stewards when rejecting a
listing that has been pended for deletion by its owner.
Closes #AMLOS-491
When denying a "pending for deletion" request the form is is misleading. Currently reads:
Return to Owner Feedback
Please provide feedback for the listing owner about what they should do to make this listing ready for publication
**How to Test**
Pull this branch
log in as bigbrother and jones.
open up the listing management page for both users. 
As jones, pend for delete one of their owned listings. 
As Bigbrother, open the listing to the admin tab and reject the listing for deletion.
Review the text given.
=> fix(management): reject deletion text change

app/js/components/management/user/RecentActivity.jsx, app/js/components/shared/ChangeLog.jsx, app/js/components/shared/PendingDeleteConfirmation.jsx, app/js/services/ListingService.js, app/js/stores/GlobalListingStore.js, app/js/webapi/Listing.js
AMLOS-449
**Description**     
As the administrator, I would like to capture the reason for deleting a listing by requiring the user to submit reason during the deletion process.
**Acceptance Criteria**   
1. include feedback form in the deletion process
2. require the user to provide feedback in order to complete the process
Log in as jones
Go to Listing Management > My Listings
Pend a listing for deletion.  Ensure that you are forced to enter a reason.
Log in as bigbrother
Go to the Administration tab of the listing.  Ensure you see the reason set by jones.
Go to Listing Management > Recent Activity.  Ensure you see the reason set by jones.
**How to test code**    
Checkout `pending_deletion_feedback` from `ozp-center`
Checkout `pending_deletion_feedback` from `ozp-backend`
=> feat(listing): require and display feedback when a user pends a listing for deletion

app/js/components/management/shared/OrgFilter.jsx
Fix to a bug created by https://github.com/aml-development/ozp-center/pull/925
When I refactored the organization tabs in Listing Management to use the short name instead of the full title in the URL, it broke the organization filter in the sidebar.  This update fixes that issue and closes AMLNG-801.
Special thanks to @mannyrivera2010 for uncovering this bug!
=> fix(listing management): use org short name when filtering by org

app/js/components/quickview/AdministrationTab.jsx, app/js/components/shared/ChangeLog.jsx, app/js/components/shared/DeleteConfirmation.jsx, app/js/components/shared/PendingDeleteConfirmation.jsx, app/js/services/ListingService.js, app/js/webapi/Listing.js
AMLOS-545
I would like to capture the reason when an app steward deletes a listing by requiring the app steward to submit a reason during the deletion process.
1. include feedback form in the deletion process
2. require the app steward to provide feedback in order to complete the process
Checkout `delete_listing_feedback` from `ozp-center`
Checkout `delete_listing_feedback` from `ozp-backend`
_Test Scenario 1_
Log in as bigbrother
Delete a listing via Listing Management
Ensure that you are required to enter a reason for deletion
Ensure that the reason displays in Listing Management > Recent Activity
_Test Scenario 2_
Log in as jones
Pend a listing for deletion
Log in as bigbrother
Go to Administration tab of listing
Approve …
=> feat(listing): require feedback when deleting a listing

app/js/components/management/mall/Categories.jsx
AMLOS-571
**Description**     
User submitted a ticket to increase the category description from 255 to a higher value.
**Acceptance Criteria**   
User can create or update a description of a category using more than 255 characters
**How to test code**    
Pull both `category_length_increase` ozp-center & ozp-backend branches
Login as a user that can create/edit categories (bigbrother)
Go to Center Settings -> Categories
Choose a category and click Edit
Verify the dialog box allows for upto 500 characters for the description.
- Says 'Max. 500 characters'
- Typing more than 500 with cause a red error
- Typing < 500 will allow for the user to submit it.
**Please Review**     
@aml-development/ozp-backend-team    
**Checklist**
=> feat(category_description): increase category description length

app/js/components/quickview/reviews/UserReviews.jsx
fixes review showing a different timestamp when editted. 
How to test:
1. Login and post a review on a certain listing.
2. Logout and login as a different user and post a review on the same listing above.
3. Logout and log back in with the account you used in step 1.
4. Edit the original review you have created. Time shouldn't change nor position.
=> fix: fix review time posted

app/styles/listing/_search-listing-tile.scss
Go to Homepage
There are some app listings that display a blown up version of small banner in thumbnail.
View on Homepage. 
Should have images fit within div now.
=> fix: fix the small banner icon not resizing within div
